#!/bin/sh
cat <<\EOF
45 49 54 41 21
___________.___________________ ._.
\_   _____/|   \__    ___/  _  \| |
 |    __)_ |   | |    | /  /_\  \ |
 |        \|   | |    |/    |    \|
/_______  /|___| |____|\____|__  /_
        \/                     \/\/
01000101 01001001 01010100 01000001 00100001
███████╗██╗████████╗ █████╗ ██╗
██╔════╝██║╚══██╔══╝██╔══██╗██║
█████╗  ██║   ██║   ███████║██║
██╔══╝  ██║   ██║   ██╔══██║╚═╝
███████╗██║   ██║   ██║  ██║██╗
╚══════╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝
............................................

Apply automatic code formatting ...
EOF
set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

files=$(git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.java$" || true)
if [ ! -z "${files}" ]; then
    comma_files=$(echo "$files" | paste -s -d "," -)
    "${REPO_ROOT_DIR}/gradlew" goJF -DgoogleJavaFormat.include="$comma_files" &>/dev/null
    git add $(echo "$files" | paste -s -d " " -)
fi
cat <<\EOF
Executing unit tests...
EOF
"${REPO_ROOT_DIR}/gradlew" test